### ISSUE TITLE
未使用のpropsについて

### ISSUE THREAD

**Issue by mizushima1226** [kbtrg/TodoApplication--React.ver#1]
https://github.com/kbtrg/TodoApplication--React.ver/blob/0e9e0c5e4abe6f35922b39caf5ae0ce72379bbcf/src/layout/input.jsx#L49

modalTypeが未使用なので除去してOKと思います👀

**Comment by kbtrg** [comment]
https://github.com/kbtrg/TodoApplication--React.ver/issues/2
こちらのissue2でご指摘いただいた、modalの分別をmodalTypeによって、分けようかなと思います。
