### ISSUE TITLE
Modalのコンポーネント設計について

### ISSUE THREAD

**Issue by mizushima1226** [kbtrg/TodoApplication--React.ver#2]
https://github.com/kbtrg/TodoApplication--React.ver/blob/0e9e0c5e4abe6f35922b39caf5ae0ce72379bbcf/src/layout/input.jsx#L15

https://github.com/kbtrg/TodoApplication--React.ver/blob/0e9e0c5e4abe6f35922b39caf5ae0ce72379bbcf/src/layout/input.jsx#L23

`'登録完了', `Todoリストに【${text}】を追加しました。`, '閉じる'`
のように配列をステートに持たせて、モーダルに渡しているかと思います

1. propsを見直す

登録完了→モーダルのタイトル
Todoリストに【${text}】を追加しました。→モーダルのbody部分にあたる文章
閉じる→モーダルのアクションボタン

となっているので、それぞれ
モーダルのタイトルはprops.title
文章とボタンはprops.children
で受け取れるようなコンポーネントにすると汎用性が高くなります

コンポーネントの実装も
mesList[0]などとなっていて、何を意味しているかが分かりにくくなっています

また「閉じる」についてはモーダルとして共通の機能かと思うので、propsで渡すのではなく、モーダルコンポーネント側で「閉じる」ボタンをして実装してしまって良いと思いました

2. モーダルを２つに分ける
時と場合によりますが、ここでは「登録完了」と「クリア完了」のモーダルは分けてしまってもいいかもしれません

1番2番対応できれば使いやすいモーダルコンポーネントになりそうです💡

わからないところ、追加で質問してもらえるとです🙏

**Comment by kbtrg** [comment]
良く分かりました！対応していきます！
