### ISSUE TITLE
ボタンコンポーネントを作ったほうが良い

### ISSUE THREAD

**Issue by mizushima1226** [kbtrg/TodoApplication--React.ver#5]
https://github.com/kbtrg/TodoApplication--React.ver/blob/0e9e0c5e4abe6f35922b39caf5ae0ce72379bbcf/src/component/todoItems.jsx#L23-L28

似たようなコードが書かれているところ見受けられます
どんなプロジェクトでもボタンはコンポーネント化されるので良い練習になると思います〜
- スタイルを共通化でき、変更に強い
- ボタンとしての振る舞いを共通管理できる（非活性化・ローディング時などなど）

**Comment by kbtrg** [comment]
確かにコンポーネント化するべき点ですね！
コードが見やすくなりました。コンポーネント化できる所を探しながらコードを組んでいきます！
